---
- name: Install docker
  ansible.builtin.package:
    name: docker
    state: present
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker
- name: Enable docker service and ensure it is running
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started
